Add support for docker volumes
NIAEFEUP/niployments-old pull request #27
Opened 2022-02-09 09:26 UTC by bdmendes

Needs to be tested in the server.

2022-02-09 17:20 UTC, DoStini requested changes

2022-02-09 17:20 UTC, DoStini commented on deployments/project-configs.sh
> +project_docker_volume[nijobs-be---master]='/home/ni/niployments/deployments/static/nijobs:/static'
instead of `static` should be `/usr/src/app/static`

2022-02-09 17:20 UTC, DoStini commented on deployments/project-configs.sh
> +project_docker_volume[nijobs-be---develop]='/home/ni/niployments/deployments/static/nijobs:/static'
same here

2022-02-09 23:45 UTC, miguelpduarte requested changes
Just some suggestions and questions for debate.

Also, since it seems that the pipeline is not doing this for some reason (I thought I had configured it to do so 🤔), please run [shellcheck](https://github.com/koalaman/shellcheck/) on the scripts just to make sure everything is fine and paste the results here. Thanks.

2022-02-09 23:45 UTC, miguelpduarte commented on deployments/deploy-types.sh
> +    # Deploying project Docker container
Unnecessary comment, the echo already mentions what is concretely hapenning (running the new image as a container).

2022-02-09 23:45 UTC, miguelpduarte commented on deployments/deploy-types.sh
> +    fi
This can probably be simplified using a variable expansion.

Something like
```bash
docker run -d (...) "${docker_volume:+-v $docker_volume}"
```

Should work.

See the [default values section in devhints](https://devhints.io/bash#parameter-expansions) for more information on how this works.

Maybe it would make sense to have some ability to pass in arbitrary docker options, to generalise this feature, instead of focusing specifically on volumes. I'm not sure about the necessity of this though, what do you think? (Also pinging @DoStini @imnotteixeira for opinions on potential use cases here)

Also please test the above suggestion with actual command execution. I don't have access to a linux device right now to test this thoroughly, but it seemed to work with some dummy examples in my windows git bash shell.

2022-02-09 23:45 UTC, miguelpduarte commented on deployments/deploy-types.sh
> +    fi
A potential indicator that this may be useful is that this solution would already not work for passing in multiple volumes to the same container, for example.

2022-02-09 23:45 UTC, miguelpduarte commented on deployments/project-configs.sh
> +project_docker_volume[nijobs-be---develop]='/home/ni/niployments/deployments/static/nijobs:/usr/src/app/static'
What is docker's behaviour when a folder used in a volume does not previously exist? Is it created or is there an error?

If there is a need to create the directory before the app is deployed that should be reflected in `deployments/README.md` in my opinion, so as to document all of the necessary steps to adding / configuring deployments.

2022-02-09 23:46 UTC, miguelpduarte commented
(Nevermind the comment about shellcheck, it seems that I confused myself with the Makefile lol)

2022-02-11 15:23 UTC, bdmendes commented on deployments/deploy-types.sh
> +    fi
I'm thinking of renaming the variable to docker_flags, to make this flexible and simple. Would that be ok?

2022-02-11 15:24 UTC, bdmendes commented on deployments/deploy-types.sh
> +    fi
I will test your suggestion on variable expansion and report back later.

2022-02-11 15:29 UTC, bdmendes commented on deployments/project-configs.sh
> +project_docker_volume[nijobs-be---develop]='/home/ni/niployments/deployments/static/nijobs:/usr/src/app/static'
There's no need, Docker does create the directory if it does not exist.

2022-03-10 11:21 UTC, DoStini requested changes

2022-03-10 11:21 UTC, DoStini commented on deployments/project-configs.sh
> +project_docker_flags[nijobs-be---develop]='-v /home/ni/niployments/deployments/static/nijobs:/usr/src/app/static'
I think this should be different folders

2022-03-14 17:40 UTC, DoStini approved these changes

2022-03-15 19:22 UTC, miguelpduarte requested changes
Does not work for multiple docker arguments. I had no issue with this PR only tackling volumes and the next PR making the config more modular to allow for arbitrary docker flags.

However, as it stands, this cannot be merged since it will cause further configuration to break.

We should either fix this to work for multiple arguments or rollback to just configuring volumes.

2022-03-15 19:22 UTC, miguelpduarte commented on deployments/deploy-types.sh
> +    docker run "${docker_flags:-}" -d --restart=unless-stopped --env PORT=80 -p "$port:80" "$image_tag"
This will not work for multiple space-separated arguments, a simple example showcasing this:

![image](https://user-images.githubusercontent.com/5095627/158453899-9ddb3f38-aae5-42c9-a943-25871e424bfd.png)

This has to do with the way that Bash [expands quoted variables](https://stackoverflow.com/questions/39583838/bash-pass-variable-as-argument-with-quotes). Using strings to ensure that the variable would not be expanded into several arguments is usually the way to go, but it seems that in this instance it may be necessary to remove the quotes? Let's see if the shellcheck page for this issue has any suggestions.

2022-03-15 19:22 UTC, miguelpduarte commented on deployments/deploy.sh
> +    # Passing in the configs from ./project-configs.sh. dotenv_location and docker_volume might not be set so sending instead an empty variable ("") so that the 'unbound variable' error does not occu
Docker flags != docker_volume

2022-03-15 19:22 UTC, miguelpduarte commented on deployments/deploy.sh
> +    deploy_default "$project" "$branch" "${project_port[$project---$branch]}" "${project_dotenv_location[$project---$branch]:-}" "${project_docker_volume[$project---$branch]:-}"
Once again, it's not a volume anymore

2022-03-15 19:22 UTC, miguelpduarte commented on deployments/project-configs.sh
> +project_docker_flags[nijobs-be---master]='-v /home/ni/niployments/deployments/static/nijobs:/usr/src/app/static'
Maybe the configured static folder should be added to the README as a "standard" location for container volumes? Thus maybe it should be something like `/home/ni/niployments/deployments/volumes-data/nijobs/static` maybe?

@DoStini opinions?

2022-03-15 19:22 UTC, miguelpduarte commented on deployments/project-configs.sh
> +project_docker_flags[nijobs-be---develop]='-v /home/ni/niployments/deployments/static/nijobs-beta:/usr/src/app/static'
Same as above, considering the path.

2022-03-15 19:26 UTC, miguelpduarte commented on deployments/deploy-types.sh
> +    docker run "${docker_flags:-}" -d --restart=unless-stopped --env PORT=80 -p "$port:80" "$image_tag"
Found it: https://github.com/koalaman/shellcheck/wiki/SC2086

The exceptions section seems to have the solution to the issue.

2022-03-15 19:31 UTC, miguelpduarte commented on deployments/deploy-types.sh
> +    docker run "${docker_flags:-}" -d --restart=unless-stopped --env PORT=80 -p "$port:80" "$image_tag"
Tested this with the same example case:
```bash
#!/usr/bin/env bash

# Just string
a="-l -c"

wc "$a" ~/.bashrc

# Bash array
a=(-l -c)

wc "${a[@]}" ~/.bashrc
```

The first option causes an error in argument parsing, while the second one works perfectly. Now we should test how this works with passing arguments into the deployment function, since I'm guessing that the array might expand into several arguments... Maybe we can keep using `shift` to pop arguments as we assign them to local variables and then use `$@` for the rest?

2022-03-15 19:34 UTC, miguelpduarte commented on deployments/deploy-types.sh
> +    docker run "${docker_flags:-}" -d --restart=unless-stopped --env PORT=80 -p "$port:80" "$image_tag"
Using this in the configuration might cause some issues as well:

```bash
miguel@miguel-xps$ testkv[key---morekey]=(-l -c)
bash: testkv[key---morekey]: cannot assign list to array member
```

I'm thinking that reverting this to only targeting a single docker volume per deployment might be best for now (I'm not sure if with this issue it is even possible to support several volumes at once) since it solves the current issue right now. Later on we can further expand after we have a working PoC.

2022-03-15 19:59 UTC, DoStini commented on deployments/project-configs.sh
> +project_docker_flags[nijobs-be---master]='-v /home/ni/niployments/deployments/static/nijobs:/usr/src/app/static'
Seems good, but maybe something like `.../volumes-data/nijobs/beta` and `.../volumes-data/nijobs/production` or somethign like that

2022-03-15 19:59 UTC, DoStini commented on deployments/project-configs.sh
> +project_docker_flags[nijobs-be---master]='-v /home/ni/niployments/deployments/static/nijobs:/usr/src/app/static'
It doesn't need to be named static

2022-03-28 11:11 UTC, miguelpduarte approved these changes
`xargs` seems like it would work here:

![image](https://user-images.githubusercontent.com/5095627/160385976-eefaeab0-76e8-4c0d-8f9c-82b2af0438d9.png)

We just need to be mindful of spaces, potentially quoting the passed in flags, as necessary.

2022-03-28 11:15 UTC, merged